### PR TITLE
GlobalNewFilesInsertJob: Check if file exists and if it does update the table

### PR DESCRIPTION
**Pull request by paladox**
Rather than inserting new entries, update existing entries.

### CODE REVIEW

**Comment by paladox** [comment]
> https://doc.wikimedia.org/mediawiki-core/master/php/interfaceWikimedia_1_1Rdbms_1_1IDatabase.html#a8d6992306577d84c6eac1eed6c04f325

@BlankEclair so instead of ->update I should use ->upsert? Still not fully sure how to use it.

**Comment by BlankEclair** [comment]
Yes--An upsert is basically UPDATE if it exists, otherwise INSERT (but in an atomic fashion)

**Comment by paladox** [comment]
Is it like this?

```
		$dbw->upsert(
			'gnf_files',
			[
 				'files_timestamp' => $dbw->timestamp(),
 				'files_url' => $uploadedFile->getFullUrl(),
 				'files_uploader' => $this->userId,
			],
			[ [ 'files_name' ] ],
			[
 				'files_dbname' => WikiMap::getCurrentWikiId(),
 				'files_name' => $uploadedFile->getName(),
			]
		);
```

**Comment by BlankEclair** [comment]
I think you need all the new rows in the second argument?

Example: https://github.com/miraheze/ManageWiki/blob/fd4ddd50621cd11542ce1321bc57c40a28d3978b/includes/Helpers/ManageWikiExtensions.php#L232-L248

I haven't used MediaWiki's upsert function, so I don't know

**Comment by paladox** [comment]
@BlankEclair please re-review :)

**Comment by BlankEclair** [comment]
Um... I mean do an upsert call, without checking if the row exists, as upsert would do that

**Comment by paladox** [comment]
Oh wait, we shouldn’t us upsert. We don’t use the unique thing in the sql thus this will just insert a new entry. We want to update, not insert. It falls back to updating if it throws an error on trying to insert a new entry but there’s an existing one… if we don’t use the unique thing in the sql, it doesn’t do that.

**Pull request merged**
