### PR TITLE
Update GlobalNewFilesMoveJob: Check if file exists in table before updating it

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by BlankEclair** [comment]
Why though? Does this throw an exception otherwise?

**Comment by paladox** [comment]
> Why though? Does this throw an exception otherwise?

I'd imagine it would for files pre-GlobalNewFiles.

**Comment by paladox** [comment]
Better to have a check incase.

**Comment by BlankEclair** [comment]
What happens if the file isn't there?

**Comment by paladox** [comment]
> What happens if the file isn't there?

I'd image the delete throws an exception or something as it wouldn't be in the table. It wouldn't have any impact on public facing because it's a job. But still.

**Comment by BlankEclair** [comment]
It's an update though, and I don't see why MediaWiki should throw on no rows affected, plus:
```
> docker compose exec mediawiki php maintenance/run.php shell
PHP Notice:  Writing to directory /.config/psysh is not allowed. in /var/www/html/w/vendor/psy/psysh/src/ConfigPaths.php on line 327
Psy Shell v0.12.4 (PHP 8.1.20 — cli) by Justin Hileman
> $dbw = \MediaWiki\MediaWikiServices::getInstance()->getConnectionProvider()->getPrimaryDatabase( 'virtual-globalnewfiles' );
= Wikimedia\Rdbms\DBConnRef {#6476}

> $dbw->update( 'gnf_files', [ 'files_name' => 'these are invalid characters: <>|{}' ], [ 'files_dbname' => 'homosexualcity' ] );
= true
```

**Pull request closed without merging**
